// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADM6iqpVpE204hkJzvpt7kZyNoz9ftK94',
    appId: '1:602086491447:web:2970df3caf7c642b2506b2',
    messagingSenderId: '602086491447',
    projectId: 'tazg-6644c',
    authDomain: 'tazg-6644c.firebaseapp.com',
    storageBucket: 'tazg-6644c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_t9g4RKTf19bWFCZB5_AJEDcpuYxmOvs',
    appId: '1:602086491447:android:fd03087484c5c2f12506b2',
    messagingSenderId: '602086491447',
    projectId: 'tazg-6644c',
    storageBucket: 'tazg-6644c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-tWQrDBA8ui-5ZXC7q41fDeOWYygIJm0',
    appId: '1:602086491447:ios:b37128ce003fcf9b2506b2',
    messagingSenderId: '602086491447',
    projectId: 'tazg-6644c',
    storageBucket: 'tazg-6644c.firebasestorage.app',
    androidClientId: '602086491447-d4j56m8qbunclc2dovbd7586tqdsgrav.apps.googleusercontent.com',
    iosClientId: '602086491447-ah5cai00s964p36gmjq3c3j15bvcuqlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.maps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-tWQrDBA8ui-5ZXC7q41fDeOWYygIJm0',
    appId: '1:602086491447:ios:b37128ce003fcf9b2506b2',
    messagingSenderId: '602086491447',
    projectId: 'tazg-6644c',
    storageBucket: 'tazg-6644c.firebasestorage.app',
    androidClientId: '602086491447-d4j56m8qbunclc2dovbd7586tqdsgrav.apps.googleusercontent.com',
    iosClientId: '602086491447-ah5cai00s964p36gmjq3c3j15bvcuqlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.maps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADM6iqpVpE204hkJzvpt7kZyNoz9ftK94',
    appId: '1:602086491447:web:10bdaf05f8d800122506b2',
    messagingSenderId: '602086491447',
    projectId: 'tazg-6644c',
    authDomain: 'tazg-6644c.firebaseapp.com',
    storageBucket: 'tazg-6644c.firebasestorage.app',
  );
}
